# .bashrc

export LANG=en_IE.utf8
export LC_ALL=en_IE.utf8
export LC_LANGUAGE=en_IE.utf8


# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
#PS1='[\u@\h \W]\$ '
#export PS1="[\A]{\w} \l\n[\u:\h]-> \[$(tput sgr0)\]"
export PS1="\u@\h:\A \W-> \[$(tput sgr0)\]"
