
if [ -e /home/$USER/.fontsupd ]; then
 echo  ; 
 else
  mkfontscale /home/void/.fonts
  mkfontdir /home/void/.fonts
  fc-cache -f -v 
  xset +fp /home/void/.fonts
  xset fp rehash
  touch /home/$USER/.fontsupd

fi

#loadkeys /usr/share/kbd/keymaps/i386/qwerty/uk.map.gz &

#Below line is for dual displays
#xrandr --output eDP1 --mode 1280x1024 --output HDMI2 --mode 1280x1024

tint2 &
hsetroot -fill /home/$USER/autovoid/autoscript/wallpapers/Mass\ Effect\ Wallpapers/Image\ 58.jpg
compton --config /home/$USER/conkyconfigs/compton.conf  &
setxkbmap -layout ie &
#( sleep 3; thingmenu -s -x -ws 2 -hs 1 Xterm xterm filer "rox ~" "FB Msgs" pidgin; ) &
conky -c /home/$USER/conkyconfigs/conkycpu.conf &
#conky -c /home/$USER/conkyconfigs/conkynet.conf &
conky -c /home/$USER/conkyconfigs/conkytime.conf &
conky -c /home/$USER/conkyconfigs/conkysys.conf &
fluxbox
